version: "3.7"

services:
  slate-frontend:
    image: slate-frontend
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - "8001:80"

networks:
  default:
    external:
      name: aqua
